# Generated by Django 5.1.4 on 2026-07-01 16:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('content', models.TextField()),
                ('excerpt', models.CharField(blank=True, max_length=400)),
                ('category', models.CharField(choices=[('Techniques', 'Techniques'), ('Sustainability', 'Sustainability'), ('Product Care', 'Product Care'), ('News', 'News'), ('Other', 'Other')], default='Other', max_length=50)),
                ('image', models.FileField(blank=True, null=True, upload_to='')),
                ('is_published', models.BooleanField(default=False)),
                ('read_time', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
